spring.application.name=springBoot-jdbc-demo

spring.datasource.url=jdbc:postgresql://localhost:5433/demo
spring.datasource.username=postgres
spring.datasource.password=postgres123
spring.datasource.driver-class-name=org.postgresql.Driver